### ISSUE TITLE
"A Javascript Error occured in Main process"

### ISSUE THREAD

**Issue by ghost** [KentCompSoc/KentFlixDesktopApp#2]
**Describe the bug**
Javascript errors show up after trying to start the Electron app.

**To Reproduce**
1. Run ``npm start``
2. See error

**Expected behavior**
App to launch and run properly

**Screenshots**
![image](https://user-images.githubusercontent.com/14107316/48744760-7e03e480-ec60-11e8-9f08-f9e58e18de1a.png)

![image](https://user-images.githubusercontent.com/14107316/48744640-f1f1bd00-ec5f-11e8-9904-3923e7be54b7.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS, Windows, Ubuntu] Windows 10 64 Bit
 - OS Version: [e.g. 10.12, 10.0.17763.1, 18.04.1 LTS] 10.0.17763.134
 - KentFlix DesktopApp Version [e.g. 0.1.0] N/A development testing version
 - KentFlix WebClient version [e.g. 0.1.0] N/A development testing version

**Comment by ghost** [comment]
@HenryBrown0  Do you have any idea what might be causing the issue?

It's literally just requiring Index.js (in KentFlix Client submodule) from Electron.

**Comment by HenryBrown0** [comment]
Kent Flix is no longer maintained so closed this
